### PR TITLE
Fix ChromePicker layout shift

### PR DESCRIPTION
**Pull request by minnayu**
#19 
Add style to ChromePicker to prevent layout shift. Please let me know if this is sufficient. Thank you!

### CODE REVIEW

**Comment by minnayu** [comment]
For a visual, attached is a screenshot of the change I made. The ChromePicker opens up over the interface to prevent the layout shift.

Screen Shot 2023-03-27 at 10 09 34 PM

**Comment by ShashwatAgrawal20** [comment]
Can you also make it shut when clicked somewhere else or after picking the color.

**Comment by minnayu** [comment]
Yes I will work on that feature!

**Comment by ShashwatAgrawal20** [comment]
LGTM, Thanks for contributing

giphy

**Pull request merged**
